#!/bin/bash

echo "Enter two numbers"
read a
read b

echo "Enter the math operation u want"
echo "Press a for addition"
echo "press m for multiplication"
echo "press s for substraction"
echo "press d for Division "

read T
case $T in
	a)echo "the addition of $a and $b is $(($a + $b))"
;;
m)echo "The multiplication of $a and $b is $(($a * $b))"
;;
s)echo "the substraction of $a and $b is $(($a - $b))"
;;
d)echo "the division of $a and $b is $(($a / $b))"
;;
*)echo "Press the prescribed keys only"
;;
esac
