#!/bin/bash

echo "Enter the salary"
read sal

if [ $sal -lt 20000 ]
then
echo "No tax"
elif [ $sal -eq 20000 ]
then
echo " 2% tax"
elif [ $sal -gt 20000 ] && [ $sal -le 40000 ]
then
 echo "5% tax"
elif [ $sal -gt 40000 ]
then
 echo "10% tax"
 fi
