#!/bin/bash

echo "Enter your Age"
read age

if [ $age -lt 13 ]
then
echo "You are a child "
elif [ $age -ge 13 ] && [ $age -le 19 ]
then
echo "You are a teenager"
elif [ $age -ge 20 ]
then
echo "You are an adult"
fi
